"""Initial migration

Revision ID: 788d01b4c8ef
Revises: 
Create Date: 2026-07-28 19:45:19.541817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788d01b4c8ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_gpu_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('ssh_key_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('last_used_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('dataset_path', sa.Text(), nullable=False),
    sa.Column('use_bg_injection', sa.Boolean(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('train_val_split', sa.Float(), nullable=False),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.Column('remote_gpu_profile_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remote_gpu_profile_id'], ['remote_gpu_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_name', sa.String(length=150), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('dataset_path', sa.Text(), nullable=False),
    sa.Column('dataset_version_tag', sa.String(length=100), nullable=True),
    sa.Column('use_bg_injection', sa.Boolean(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('train_val_split', sa.Float(), nullable=False),
    sa.Column('run_mode', sa.String(length=20), nullable=False),
    sa.Column('remote_gpu_profile_id', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_expression', sa.String(length=100), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('airflow_dag_id', sa.String(length=150), nullable=False),
    sa.Column('airflow_dag_run_id', sa.String(length=150), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remote_gpu_profile_id'], ['remote_gpu_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_history_created_at', 'run_history', ['created_at'], unique=False)
    op.create_index('idx_run_history_model_name', 'run_history', ['model_name'], unique=False)
    op.create_index('idx_run_history_status', 'run_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_history_status', table_name='run_history')
    op.drop_index('idx_run_history_model_name', table_name='run_history')
    op.drop_index('idx_run_history_created_at', table_name='run_history')
    op.drop_table('run_history')
    op.drop_table('last_used_config')
    op.drop_table('remote_gpu_profiles')
    # ### end Alembic commands ###
